[project]
name = "thesis-template"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mikkel Roald-Arbøl <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]
render-typst = "typst compile examples/examploe-typst/main.typ --root ../.."
render-myst = "myst build --typst"

[dependencies]
typst = ">=0.11.0,<0.12"
mystmd = ">=1.2.0,<1.3"
